import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { isAdminAuthenticated } from "@/lib/admin-auth"
import { logAudit } from "@/lib/audit"
import { trackEvent } from "@/lib/analytics"
import { rateLimit, getClientIp, RATE_LIMITS } from "@/lib/rate-limit"
import { createMatchSchema, updateMatchSchema } from "@/lib/validation"

export async function GET() {
  await prisma.match.updateMany({
    where: { status: "upcoming", date: { lte: new Date() } },
    data: { status: "live" },
  })
  const matches = await prisma.match.findMany({
    include: { team1: true, team2: true, season: true, innings: true, performances: { include: { player: true } } },
    orderBy: { date: "asc" },
  })
  return NextResponse.json(matches)
}

export async function POST(req: Request) {
  if (!(await isAdminAuthenticated())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const ip = getClientIp(req)
  const rl = rateLimit(`match_write:${ip}`, RATE_LIMITS.GENERAL_WRITE)
  if (!rl.allowed) return NextResponse.json({ error: "Too many requests." }, { status: 429 })

  const body = await req.json()
  const parsed = createMatchSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 })
  }

  const data = parsed.data
  const seasonId = data.seasonId
  let matchNo = data.matchNo
  if (seasonId && !matchNo) {
    const last = await prisma.match.findFirst({
      where: { seasonId },
      orderBy: { matchNo: "desc" },
      select: { matchNo: true },
    })
    matchNo = (last?.matchNo ?? 0) + 1
  }

  const match = await prisma.match.create({
    data: {
      seasonId: data.seasonId,
      team1Id: data.team1Id,
      team2Id: data.team2Id,
      matchNo: matchNo || 0,
      stage: data.stage || "league",
      date: new Date(data.date),
      venue: data.venue,
      tossWinner: data.tossWinner || "",
      tossDecision: data.tossDecision || "",
      youtubeUrl: data.youtubeUrl || "",
      umpire1: data.umpire1 || "",
      umpire2: data.umpire2 || "",
      thirdUmpire: data.thirdUmpire || "",
      matchReferee: data.matchReferee || "",
      officialScorer: data.officialScorer || "",
      tossTime: data.tossTime || "",
      matchStartTime: data.matchStartTime || "",
      delayReason: data.delayReason || "",
    },
  })

  logAudit({ action: "match_created", entity: "match", entityId: match.id, details: JSON.stringify({ matchNo, teams: [data.team1Id, data.team2Id] }), ip })

  return NextResponse.json(match)
}

export async function PATCH(req: Request) {
  if (!(await isAdminAuthenticated())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const ip = getClientIp(req)

  const rl = rateLimit(`match_write:${ip}`, RATE_LIMITS.GENERAL_WRITE)
  if (!rl.allowed) return NextResponse.json({ error: "Too many requests." }, { status: 429 })

  const body = await req.json()
  const parsed = updateMatchSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 })
  }

  const { id, override, ...data } = parsed.data

  if ((data.tossWinner !== undefined || data.tossDecision !== undefined) && !override) {
    const inningsStarted = await prisma.inning.findFirst({
      where: { matchId: id, ballsData: { not: "[]" } },
      select: { id: true },
    })
    if (inningsStarted) {
      return NextResponse.json(
        { error: "Toss is locked once the match has started. Use the admin override to force a change." },
        { status: 400 }
      )
    }
  }

  const updateData: Record<string, unknown> = { ...data }
  if (data.date) updateData.date = new Date(data.date)

  const match = await prisma.match.update({ where: { id }, data: updateData })

  logAudit({ action: "match_updated", entity: "match", entityId: id, details: JSON.stringify(Object.keys(data)), ip })

  if (data.status === "completed") {
    logAudit({ action: "match_completed", entity: "match", entityId: id, details: JSON.stringify({ result: data.result, manOfMatch: data.manOfMatch }), ip })
    trackEvent("match_completed", { matchId: id, result: data.result || "" }, ip)
    const fullMatch = await prisma.match.findUnique({
      where: { id },
      select: { seasonId: true },
    })
    if (fullMatch) {
      const { recalcPointsTable, recalcPlayerStats } = await import("@/lib/stats")
      await recalcPointsTable(fullMatch.seasonId)
      await recalcPlayerStats()
      try {
        const { maybeAutoGenerateSeasonQuiz } = await import("@/lib/season-quiz")
        const quizResult = await maybeAutoGenerateSeasonQuiz(fullMatch.seasonId)
        if (quizResult.autoGenerated) {
          logAudit({ action: "season_quiz_auto_generated", entity: "season", entityId: fullMatch.seasonId, details: JSON.stringify({ count: quizResult.count }), ip })
        }
      } catch (quizErr) {
        console.error("Season quiz auto-generation failed:", quizErr)
      }
    }
  }

  if (data.status === "live" || data.status === "super_over") {
    await prisma.match.update({ where: { id }, data: { isSquadLocked: true } })
    logAudit({ action: "squad_locked", entity: "match", entityId: id, details: JSON.stringify({ status: data.status }), ip })
  }

  return NextResponse.json(match)
}

export async function DELETE(req: Request) {
  if (!(await isAdminAuthenticated())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const ip = getClientIp(req)

  const rl = rateLimit(`match_write:${ip}`, RATE_LIMITS.GENERAL_WRITE)
  if (!rl.allowed) return NextResponse.json({ error: "Too many requests." }, { status: 429 })

  const { id } = await req.json()
  const match = await prisma.match.findUnique({ where: { id }, select: { status: true, seasonId: true, team1Id: true, team2Id: true } })
  await prisma.playerMatch.deleteMany({ where: { matchId: id } })
  await prisma.match.delete({ where: { id } })

  logAudit({ action: "match_deleted", entity: "match", entityId: id, details: JSON.stringify({ wasStatus: match?.status }), ip })

  if (match?.status === "completed") {
    const { recalcPointsTable, recalcPlayerStats } = await import("@/lib/stats")
    await recalcPointsTable(match.seasonId)
    await recalcPlayerStats()
  }
  return NextResponse.json({ success: true })
}
